CREATE TABLE EVENTO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	NOME			NVARCHAR(150)		NOT NULL,
	DATA			DATE				NOT NULL,
	HORA			TIME				NOT NULL,
	DESCRICAO		NVARCHAR(500)		NOT NULL,
	PRIORIDADE		INTEGER				NOT NULL,
	DATAINCLUSAO	DATETIME			NOT NULL,
	DATAALTERACAO	DATETIME			NOT NULL,
	ATIVO			INTEGER				NOT NULL DEFAULT(1),
	PRIMARY KEY(ID))
GO